name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Download clangd
        run: |
          curl -L https://github.com/clangd/clangd/releases/download/15.0.6/clangd-linux-15.0.6.zip > clangd.zip
          unzip clangd.zip
      - name: Build with Maven
        run: |
          export DISPLAY=:99
          export PATH=$PWD/clangd_15.0.6/bin:$PATH
          echo $PATH
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          mvn -B -V -X -e clean verify
